### ISSUE TITLE
Diagram not printing correctly

### ISSUE THREAD

**Issue by AccidentalGenius101** [csgoh/processpiper#12]
First of all its a very great library you built! My issue is that when I save my diagram it misses content on the right. The output image is 3642x1095

**Comment by csgoh** [comment]
Can you provide your code to reproduce the issue? And what platform you are running your code on?

**Comment by csgoh** [comment]
@AccidentalGenius101 This is an easy fix. Just add `width` argument to the ProcessMap parameter. See code below: 

```
with ProcessMap(
    "Title", colour_theme="BLUEMOUNTAIN", width=4800) as my_process_map:
    with my_process_map.add_pool("Pool") as pool1:
```
The default width is just 3200, you can always extend it.

**Comment by AccidentalGenius101** [comment]
Cool thank you for the quick help!
