### ISSUE TITLE
the last part of the generated diagram won't be shown is the diagram is too long

### ISSUE THREAD

**Issue by ShuaiweiYu** [csgoh/processpiper#15]
Hi there, 

This library is very cool, and I'm using it for my thesis. Yet, if the generated diagram is too long, then the last part of the diagram is not shown but is displayed in grey colour.

I'm using macOS 13.4
my python version is 3.10

for example, 
I used such text to render 

title: debug01
colourtheme: BLUEMOUNTAIN
lane: customer
	(start) as start
	[brings a defective computer] as activity_9
lane: crs
	[checks the defect] as activity_10
	[hand out a repair cost calculation] as activity_11
	<the customer decides> as gateway_1
	[are acceptable] as activity_3
	[continues] as activity_4
	[takes her computer] as activity_5
	[consists of two activities] as activity_12
	[execute two activities in an arbitrary order] as activity_13
	[is] as activity_14
	[check the hardware] as activity_15
	[repair the hardware] as activity_16
	[checks the software] as activity_17
	[configure the software] as activity_18
	[test the proper system functionality after each of these activities] as activity_19
	<detect an error> as gateway_6
	[execute another arbitrary repair activity] as activity_8
	(end) as end

start->activity_9->activity_10->activity_11->gateway_1
gateway_1->activity_3->activity_4->activity_12
gateway_1->activity_5->activity_12
activity_12->activity_13->activity_14->activity_15->activity_16->activity_17->activity_18->activity_19->gateway_6
gateway_6->activity_8->end
gateway_6->end

and the output looks like this
![text01_test 16 42 27](https://github.com/csgoh/processpiper/assets/71372489/8e783120-7e12-4b83-adf9-915f3ff0ff24)

**Comment by ShuaiweiYu** [comment]
I saw that in the closed issues that an extra parameter "width=4800" can be given in "with ProcessMap", is there also such an option when using render()?

**Comment by csgoh** [comment]
hi @ShuaiweiYu, unfortunately the `width` option is not current supported in the render() method. I will add that option in next release. Meantime, can you use the generated code that you can get from the render() method and manually add in the `width` option for now? You would have to run the python code instead of calling the render.

**Comment by ShuaiweiYu** [comment]
yeah, sure. Thanks for the quick response! I know it is not encouraged to change source code, but I changed the default width in the processmap to a larger number, and it currently fixed my problem.

**Comment by csgoh** [comment]
@ShuaiweiYu v0.4.1 is now released. You can now specify the width. E.g. `width: 8190`. 

See Wiki for information: https://github.com/csgoh/processpiper/wiki/Usage-Documentation
