### ISSUE TITLE
ModuleNotFoundError: No module named 'processpiper'

### ISSUE THREAD

**Issue by edqu1** [csgoh/processpiper#38]
I have installed it, updated it and also checked that all the dependencies are installed, and still receive the error in the title.

I know it must not be a path problem or an installation problem of my Python bcs all other packages work.

**Comment by csgoh** [comment]
Hi,

Sorry for late reply, I am currently on holiday.

Can you provide more information? 

* Operating System
* Python version
* Folder structure
* Sample code to reproduce the error

CS

**Comment by edqu1** [comment]
Hello,

The code used is the installation test:

"""
from processpiper import version

version.__version__
"""

Using: 
Python 3.9.13 64-bit | Qt 5.15.2 | PyQt5 5.15.7 | Windows 10 

I´m not sure what info you require for the folder structure.

**Comment by csgoh** [comment]
Hi, sorry for the late response. I am on holiday currently.

There is a few things you could try:

- Upgrade your python to 3.10. 3.9 has not been officially tested.
- Follow the step below:
     a. create a new folder, let's called it 'bpmn_test'
     b. launch terminal and change directory to 'bpmn_test'
     c. in bpmn_test folder, type 'python -m venv venv
     d. run 'venv\Scripts\activate'
     e. run 'pip install processpiper'
     f. copy the sample code from https://github.com/csgoh/processpiper#method-2-generate-business-process-diagram-using-python-code and paste to a file called test.py
     g. run test.py and you should be able to get my_process_map.png generated.

**Comment by csgoh** [comment]
Closing this as I did not hear further updates from @edqu1
