### ISSUE TITLE
[Feat] Render SVG from text input

### ISSUE THREAD

**Issue by nhpf** [csgoh/processpiper#43]
Hi @csgoh, thank you for your work on `processpiper`.
It's the best OSS Diagram-as-Code solution for BPMN that I've found so far.

I have a feature idea that I believe would add value to the project.

I noticed that the `render()` function in `text2diagram.py` relies on PIL, while the `SVGPainter` class uses DrawSVG.
Then, I understand that currently there is no way to create an SVG diagram from text:

|     | From Text          | From Code          |
|-----|--------------------|--------------------|
| PNG | :heavy_check_mark:  | :heavy_check_mark: |
| SVG | :x:                | :heavy_check_mark: |

Do you think the implementation of a `text2SVGdiagram` solution is feasible?

**Comment by csgoh** [comment]
Hi @nhpf ,

Yep, I will add that to the next release. 😊

**Comment by csgoh** [comment]
Hi @nhpf, I have just released v0.7.0. You can now save output to SVG by using the `render()` method. See the change logs in wiki for more information.

**Comment by nhpf** [comment]
Thank you, @csgoh!
It works really well!
