### ISSUE TITLE
Difficulties in drawing generation.

### ISSUE THREAD

**Issue by sreekaribh** [csgoh/processpiper#45]
Hello CsGoh,
	The Processpiper library is working only for 4 connections irrespective of the incoming and outgoing paths. In my case, I have 5 connections for the single task [B] for which it is failing to draw. Regarding this issue I made few changes in the **shape.py** file [**shortest_source_coord.connected = False**] which is drawing fine but the two tasks [E, F] are overlapping after these changes. So, kindly guide me with solution. Please refer the diagram.
![Screenshot 2024-04-01 164658](https://github.com/csgoh/processpiper/assets/165657006/c2d73a62-0bc0-4ae0-847f-a3fa151771bc)

Thanks

**Comment by csgoh** [comment]
Closing the issue as there is no further response.
