### ISSUE TITLE
[bug] Missing outgoing and incoming nodes for BPMN diagrams

### ISSUE THREAD

**Issue by Charizhardt** [csgoh/processpiper#56]
Hi,

firstly, thanks for the new BPMN export #46.
This helps a lot when creating BPMN diagrams programmatically. 

When working with the BPMN files I noticed that the elements startEvent, endEvent, intermediateCatchEvent, task, subProcess, serviceTask, exclusiveGateway, inclusiveGateway and parallelGateway are missing the outgoing and incoming nodes.

Programs like Camunda do this when creating diagrams:
```xml
<bpmn:startEvent id="Event_11njzyn">
    <bpmn:outgoing>Flow_0xkujsq</bpmn:outgoing>
</bpmn:startEvent>
``` 

This is needed when analyzing BPMN files.

Could this be a feature in the future?

**Comment by csgoh** [comment]
@Charizhardt Thanks for the help! I have added the fix to v0.8.1. Sorry for taking so long to publish it.
